version: '3.8'

services:
  web:
    build: .
    ports:
      - "80:80"
    depends_on:
      - mysql_db

  mysql_db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: admin123
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
